### ISSUE TITLE
Ticking entity I java.lang.ClassCastException

### ISSUE THREAD

**Issue by TheButterbrotMan** [Fuzss/universalenchants#10]
https://bytebin.lucko.me/WG3jhE03vq

**Comment by Fuzss** [comment]
That's an incompatibility with another mod, the mixin with the failing code is not from me.

Is your modpack public by any chance so I can test it myself?

**Comment by FoggyWizard** [comment]
I actually get the same issue, but on forge. Overlapping mods between my list and his are as follows (minus the required library mods):
Artifacts (I wouldn't think that it would, but from a mod-user's perspective, you never know what'll impact what)
Biome Makeover (adds curses, might have an impact)
Botania (I think this one is possible to affect it)
Biomes You'll Go (unlikely to be culprit, mostly affects worldgen)
Chimes (unlikely to be culprit)
Chipped (unlikely to be culprit)
Comforts (unlikely to be culprit)
Cosmetic Armor (unlikely to be culprit)
Create
Create Crafts & Additions (As opposed to Create Stuff & Additions)
Create Plus (unlikely to be culprit)
Creeper Overhaul (unlikely to be culprit)
Easy Magic (This is yours and can be discounted from the list as you would have already tested it, I simply included it for the sake of completeness. I am running all of your mods.)
Ecologics
The FTB modlist standards (also unlikely)
Geckolib
Guard Villagers
Immersive Weathering
Lil' Wings
More Axolotl Variants Mod (unlikely, just adds more axolotl skins)
Macaw's Suite (I have everything but the rooves, but this as culprit is unlikely as the failure is on the trident)
More Villagers (unlikely)
Naturalist
Overweight Farming (unlikely)
Repurposed Structures (unlikely)
Twigs (unlikely)
Yung's Bridges and Extras (unlikely)
It's still kind of a long list, but I hope this helps narrow it down.

**Comment by Fuzss** [comment]
Can you please open a separate issue? I need more information like version numbers and especially the crash-report to properly look into this.

**Comment by Fuzss** [comment]
Should be resolved by now, please reopen if not.
