### ISSUE TITLE
[Bug]: Config file doesn't generate / Multishot doesn't work on Bow

### ISSUE THREAD

**Issue by mrniddala** [Fuzss/universalenchants#11]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

Latest

### Notes (Required)

Hello, I was loading the mod on my client, seems to work.
Only the Multishot doesn't seems to work on the Bow and I can't get a config file.

![image](https://user-images.githubusercontent.com/75373609/184923969-cabdc9d9-e688-4d33-9add-ee833af5e772.png)

**Comment by Fuzss** [comment]
There is no client config, only a server config. 

I‘ll look into multishot.

**Comment by mrniddala** [comment]
Ah interesting, good to know!
Thank you.

**Comment by mrniddala** [comment]
I was installing the mod now on my server (I wanted first to change the config and upload it to the server).

The mod got loaded:

![image](https://user-images.githubusercontent.com/75373609/184934450-43546975-cb1f-43c0-a467-6af28ba089f5.png)

But I still have no config file:

![image](https://user-images.githubusercontent.com/75373609/184934565-814265eb-6ce3-45e1-b2e5-1b0fbfbd1a80.png)

Seems to be a problem.

**Comment by Fuzss** [comment]
That‘s not how server config work. They are created in the world folder as they are separate per world.

**Comment by mrniddala** [comment]
Ah, thanks. Not many mods creating their config inside the world folder. Found it now, good.

**Comment by Fuzss** [comment]
The system is directly ported from Forge itself. This is the same design philosophy as vanilla's data packs.

Although I'm aware many people struggle with finding the file, it's necessary as it provides for automatically syncing the config to clients.

**Comment by Fuzss** [comment]
Also multishot is working fine for bows. The arrows are not spread out as they are with crossbows, maybe that's making it a bit confusing.
