### ISSUE TITLE
[Bug]: can't run with forge 1.19.2

### ISSUE THREAD

**Issue by PHAT00100** [Fuzss/universalenchants#12]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.0

### Notes (Required)

![2022-08-17](https://user-images.githubusercontent.com/111385709/184955766-4205b3bd-0a53-4fa7-a4c7-5a14bd98a1cb.png)

**Comment by Fuzss** [comment]
Please provide the latest.log file: https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285

Have you installed Puzzles Lib?

**Comment by PHAT00100** [comment]
I installed Puzzles Lib.
latest.log file
[latest.log](https://github.com/Fuzss/universalenchants/files/9353756/latest.log)
:

**Comment by Fuzss** [comment]
Thanks, looks like they indeed changed something for 1.19.2. I'll look into it next week.
