### ISSUE TITLE
[Crash]: Server crash after updating to 4.0.1

### ISSUE THREAD

**Issue by mrniddala** [Fuzss/universalenchants#13]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

Latest 4.0.1

### Notes (Required)

Hello, I was updating the mod from v4.0.0 to v4.0.1 and now my server is crashing.
I have just one datapack installed - DurabilityNotify from VanillaTweaks.

### Crash Report (Required)

https://pastebin.com/raw/ceAwb2Ge

**Comment by Fuzss** [comment]
Thanks, fixed. Just waiting for the new version to be approved.

**Comment by mrniddala** [comment]
Thanks 😊
