### ISSUE TITLE
[Bug]: broke mc forge vars

### ISSUE THREAD

**Issue by tofika** [Fuzss/universalenchants#14]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.1.1

### Notes (Required)

when run mc with universal_enchants-v4.1.1-1.19.1-forge.jar broke forge vars
![01](https://user-images.githubusercontent.com/247979/185748408-888ab64a-fa10-4146-b5d9-a119149b8b1b.png)
![02](https://user-images.githubusercontent.com/247979/185748411-835fa6b8-71ff-4725-9788-a47e428f22ba.png)

**Comment by Fuzss** [comment]
Thanks, fixed in v4.1.2.
