### ISSUE TITLE
[Crash]: Incompatibility with Majrusz Enchantments

### ISSUE THREAD

**Issue by Baggytrousers27** [Fuzss/universalenchants#15]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2 43.1.2

### Mod Version (Required)

UniversalEnchants-v4.2.0-1.19.2-Forge

### Notes (Required)

Forge 1.19.2 43.1.2
majrusz-library-1.19.1-2.14.0
majruszs-enchantments-1.19.1-1.7.3
PuzzlesLib-v4.2.1-1.19.2-Forge
UniversalEnchants-v4.2.0-1.19.2-Forge

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError:

### Crash Report (Required)

https://gist.github.com/Baggytrousers27/11c9ae6be89be741cff92b4bde16e318

**Comment by Fuzss** [comment]
There's not too much I can do, if made a comment on the other issue for the dev of Majrusz Enchantments: https://github.com/Majrusz/MajruszsEnchantmentsMod/issues/55

**Comment by Baggytrousers27** [comment]
Just learnt about overwrite vs Inject so this is a teaching experience for me. Need to learn how coding works at some point. Would be a genuine benefit in my daily life.
