### ISSUE TITLE
[Bug]: Ensorcellation conflict

### ISSUE THREAD

**Issue by Dr-WeiAL** [Fuzss/universalenchants#16]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

3.0.6

### Notes (Required)

When installing Ensorcellation and UniversalEnchants at the same time, the Piercing and Multishot of the bow will not work
But only minecraft bows will have this problem, bows of other mods will not have this problem

**Comment by Fuzss** [comment]
What bows from other mods specifically? Just some examples for me to test.

**Comment by Dr-WeiAL** [comment]
As long as it is not a minecraft bow, most of them can use this enchantment
If you want to give an example
All bows from The Twilight Forest, bows from Aquaculture, Livingwood Bow from Botania are no problem
Minecraft's bow, Botania's Crystal Bow not working

**Comment by Dr-WeiAL** [comment]
Well, after testing, I found that even the bow of the mod has a problem with Piercing enchantment. If you use Piercing and Multishot at the same time, you will find that only two arrows penetrate.

**Comment by Fuzss** [comment]
Should be resolved by now, please reopen if not.
