### ISSUE TITLE
Compatibility with SurvivalPlus Lightsabers

### ISSUE THREAD

**Issue by 48004800** [Fuzss/universalenchants#18]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.3

### Notes (Required)

[SurvivalPlus Lightsabers - Mods - Minecraft - CurseForge](https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers)

After installing this mod, all lightsabers cannot be enchanted

 

I tried to modify the configuration file, but it didn't work

https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers/files/3871594
0.1.6.f

**Comment by Fuzss** [comment]
Fixed in v4.2.4. There's a dedicated config option in the server config called `allow_mod_item_support` you need to manually enable though.

**Comment by 48004800** [comment]
> Fixed in v4.2.4. There's a dedicated config option in the server config called `allow_mod_item_support` you need to manually enable though.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/78255094/188353665-187cba00-86fc-4ee3-b3c8-6039a4bcbfbc.png">
![2022-09-05_11 11 54](https://user-images.githubusercontent.com/78255094/188353694-c2f9a8a2-9988-488a-8edf-f36df2475aff.png)
Unfortunately, the problem has not been solved
I will provide more information
This is the mod version I use. I don't use other mods
forge:43.1.16
https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers/files/3871594
https://www.curseforge.com/minecraft/mc-mods/survivalplus/files/3903428
https://www.curseforge.com/minecraft/mc-mods/puzzles-lib/files/3961876
https://www.curseforge.com/minecraft/mc-mods/universal-enchants-forge/files/3968593

**Comment by 48004800** [comment]
> Fixed in v4.2.4. There's a dedicated config option in the server config called `allow_mod_item_support` you need to manually enable though.

![2022-09-05_11 11 54](https://user-images.githubusercontent.com/78255094/188354792-96ea4030-4455-4194-a619-a9812d52ea78.png)
![2022-09-05_11 23 46](https://user-images.githubusercontent.com/78255094/188354803-cc74da12-ae5f-4a87-9f90-5bd0c2cd72bc.png)

**Comment by Fuzss** [comment]
Ah, forgot to mention you also need to delete the config folder `universalenchants` in `.minecraft/config` so it can regenerate, entries for the lightsabers from survival plus will automatically be added to relevant config files.

It's a bit difficult handling those custom item that can accept enchantments usually not designed for them, so this is the best I can come up with.
