### ISSUE TITLE
[Crash]: Upon starting a new world

### ISSUE THREAD

**Issue by VizarCain** [Fuzss/universalenchants#19]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

UniversalEnchants-v4.2.4-1.19.2-Forge.jar

### Notes (Required)

Minecraft crashes when I try to make a new world. The problem also occurred in UniversalEnchants-v4.2.3-1.19.2-Forge.jar

### Crash Report (Required)

https://gist.github.com/VizarCain/b5a8c7c40d3f5c7ab60c16994821e9df

**Comment by Fuzss** [comment]
Does this version work for you?

https://mega.nz/file/jJVSwTIa#-J_Z49PSuDDEAi4xW6ysk07wua09klAbr12tNu-GNII

**Comment by Fuzss** [comment]
Awesome, thanks for your help!
