### ISSUE TITLE
[Crash]: Skeleton of Doom

### ISSUE THREAD

**Issue by thehiveknight** [Fuzss/universalenchants#20]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.1

### Notes (Required)

1. Enter a cave
2. Encounter a skeleton
(It's very weird, but in both instances this happened. I can't find any other patterns.)

### Crash Report (Required)

https://gist.github.com/thehiveknight/cf9d2013c98062b33dd5aef5c73ead9e

**Comment by Fuzss** [comment]
Haha that sounds especially scary. 

You need to update Universal Enchants to the latest version.
