### ISSUE TITLE
[Crash]: When trying to create a new world with universal enchants and qu Enchantments , minecraft crashes

### ISSUE THREAD

**Issue by JohnM514** [Fuzss/universalenchants#21]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.5

### Notes (Required)

1.Open minecraft
2.Create a new world

### Crash Report (Required)

https://mclo.gs/JzmiaP0

### latest.log (Optional)

https://mclo.gs/tTXXRDO

**Comment by Fuzss** [comment]
Fixed in v4.2.6, thanks for reporting!
