### ISSUE TITLE
Compatibility with Advanced Combat

### ISSUE THREAD

**Issue by 48004800** [Fuzss/universalenchants#23]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.7

### Notes (Required)

https://www.curseforge.com/minecraft/mc-mods/advanced-combat-revitalized/files/3973012
The problem that lightsaber cannot be enchanted last time has been solved

But I found that players cannot use items in advanced combat mod to enchant lightsabers
So I can only enchant Sharpness 10 without loading this MOD

<img width="211" alt="image" src="https://user-images.githubusercontent.com/78255094/190073036-a92b8d47-5206-4fcb-bd10-7abda2f942cb.png">

**Comment by Fuzss** [comment]
It's my fault, but I can't really do anything about it on my end unfortunately (without like dedicated mod compat which is overkill for this).

But the dev of Advanced Combat can make a minor change to make both mods compatible. In their `EnchantUpgradeClass` they need to replace `EnchantingSubjectItemStack.canApplyAtEnchantingTable(this.applyEnchantment)` with `this.applyEnchantment.canApplyAtEnchantingTable(EnchantingSubjectItemStack)` twice. Nothing will change regarding the functionality of their mod, it's just going to be compatible with Universal Enchants as this allows my mixin to apply properly.

Would be nice if you could talk to them and suggest implementing this small tweak, thanks.

**Comment by 48004800** [comment]
> It's my fault, but I can't really do anything about it on my end unfortunately (without like dedicated mod compat which is overkill for this).
> 
> But the dev of Advanced Combat can make a minor change to make both mods compatible. In their `EnchantUpgradeClass` they need to replace `EnchantingSubjectItemStack.canApplyAtEnchantingTable(this.applyEnchantment)` with `this.applyEnchantment.canApplyAtEnchantingTable(EnchantingSubjectItemStack)` twice. Nothing will change regarding the functionality of their mod, it's just going to be compatible with Universal Enchants as this allows my mixin to apply properly.
> 
> Would be nice if you could talk to them and suggest implementing this small tweak, thanks.

I had already told him

**Comment by StyStatic** [comment]
Can someone explain this issue with some more detail? not sure what the problem is here.

**Comment by 48004800** [comment]
> Can someone explain this issue with some more detail? not sure what the problem is here.

https://www.curseforge.com/minecraft/mc-mods/survivalplus-lightsabers
https://www.curseforge.com/minecraft/mc-mods/advanced-combat-revitalized
Using these two MODs at the same time will make the lightsaber unable to be enchanted by the props in advanced combat

![image](https://user-images.githubusercontent.com/78255094/190553669-03e6300a-1041-498d-88a7-3a906fa0493a.png)

**Comment by StyStatic** [comment]
The suggested fix doesn't work and neither does anything else I've tried, I don't know what to do to fix it but I don't have the time to look into it until next week.

**Comment by Fuzss** [comment]
> The suggested fix doesn't work and neither does anything else I've tried, I don't know what to do to fix it but I don't have the time to look into it until next week.

Have you set `allow_mod_item_support` to `true` in the server config of Universal Enchants? Otherwise it will indeed not work.

If you would publish your code on GitHub I'd be happy to just make a PR.

**Comment by StyStatic** [comment]
Fixed the issue, also needed to delete the config folder. Posted for all Forge versions. Thanks for the help.

48004800 this version will work for your needs after curseforge approval: [https://www.curseforge.com/minecraft/mc-mods/advanced-combat-revitalized/files/3993059](https://www.curseforge.com/minecraft/mc-mods/advanced-combat-revitalized/files/3993059)
