### ISSUE TITLE
[Crash]: java.lang.StackOverflowError: Rendering screen

### ISSUE THREAD

**Issue by aking4125** [Fuzss/universalenchants#24]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.7

### Notes (Required)

Hello,

Upon loading to the main menu. The game crashes with the following crash report. Even with Not Enough Crashes, it constantly crashes over and over again. 

Removing this mod fixes this issue and the game loads to the menu correctly.

### Crash Report (Required)

https://gist.github.com/aking4125/63e287a39be95b9e1d8b1986b688cabf

### latest.log (Optional)

https://gist.github.com/aking4125/b5b27795d89ecfb8fb5e9ac48231bd98

**Comment by Fuzss** [comment]
Should be fixed in v4.2.8. Please reopen if it comes back.
