### ISSUE TITLE
[Suggestion]: Add Ability To Toggle on/off Silktouch

### ISSUE THREAD

**Issue by Baxuvis** [Fuzss/universalenchants#26]
### Suggestion (Required)

Please add a key bind feature to Toggle and Untoggle Silktouch for picks that have fortune and silktouch on them

**Comment by Fuzss** [comment]
I can see this being an issue, but a keybind for this one case is not a good solution. I'd prefer a more general approach, so maybe like a menu for each item with a bunch of toggles where you can selectively disable any enchantment on the fly.
