### ISSUE TITLE
[Bug]: Compatibility issues with Amethyst Tools Mod

### ISSUE THREAD

**Issue by 48004800** [Fuzss/universalenchants#27]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.8

### Notes (Required)
https://www.curseforge.com/minecraft/mc-mods/amethyst-tools-mod
Amethyst Trident cannot penetrate the target under the influence of Piercing

**Comment by Fuzss** [comment]
The code for vanilla tridents is not designed to be extended, so that mod you're using has to reimplement a bunch of the trident's behavior, overriding all methods from the vanilla base class where I hook in, so my changes no longer apply.

This requires mod specific support on my end, but it's not a priority.

**Comment by 48004800** [comment]
> The code for vanilla tridents is not designed to be extended, so that mod you're using has to reimplement a bunch of the trident's behavior, overriding all methods from the vanilla base class where I hook in, so my changes no longer apply.
> 
> This requires mod specific support on my end, but it's not a priority.
I understand
In short, this problem can only be solved on your side

**Comment by 48004800** [comment]
https://github.com/Fuzss/bettertridents/issues/4
The same is true of this question

**Comment by Fuzss** [comment]
If thought about it and I won't be adding mod specific support for single items like that. It's not worth the effort to me.

I'd recommend you to disable additional enchantments such as piercing from being applicable to this modded trident. You can find out here how to do that: https://github.com/Fuzss/universalenchants#excluding-entries-from-items
