### ISSUE TITLE
[Crash on launch]: Possible Incompatibility with Polymer

### ISSUE THREAD

**Issue by Desempregago** [Fuzss/universalenchants#29]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.8

### Notes (Required)

Crashes on startup. crash log says something about _NumericClientLanguage_ and about **method_4679**

### Crash Report (Required)

https://gist.github.com/Desempregago/d397c1045ca3312d167a24e5ebe24812

### latest.log (Optional)

https://gist.github.com/Desempregago/9e9bff0f5bcc531c9c6908e8bea21054

**Comment by jarocajavi** [comment]
same issue, sorry for the duplicate 
https://github.com/Fuzss/universalenchants/issues/30

**Comment by Fuzss** [comment]
Same as https://github.com/Fuzss/universalenchants/issues/17
