### ISSUE TITLE
[Bug]: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by jarocajavi** [Fuzss/universalenchants#30]
Fabric

1.19.2

4.2.8

Hello, i show you the crashreport, i just updated a few mods of my modpack and this happens.

https://pastebin.com/131PgRNS

Thanks

**Comment by jarocajavi** [comment]
I found the uncompatibility mod, eldritch-mobs-1.12.9.jar or 1.12.10
I have made a downgrade to 1.12.8 and for now it works. Maybe with that clue you can find easier the fix.

**Comment by Fuzss** [comment]
Same as https://github.com/Fuzss/universalenchants/issues/17 actually.
