### ISSUE TITLE
[Enhancement Request]: Compatibility with Apotheosis

### ISSUE THREAD

**Issue by shinji257** [Fuzss/universalenchants#34]
### Suggestion (Required)

When this mod is installed along side Apotheosis the increased enchantment levels are not permitted if the option to fix the enchant command is disabled.  Currently it uses vanilla caps since it overrides the enchant command and doesn't honor the increased levels that apotheosis gives.

Additionally I'd request that the ability to uncap the levels be decoupled from the rest of the functionality of the fix if possible.

Pack: TNP 6 1.8.0

**Comment by Fuzss** [comment]
Should be fixed in the latest v4.2.10. Can you confirm that?

**Comment by shinji257** [comment]
The uncap is decoupled but if you leave the enchant command fix enabled it doesn't import the new level caps from Apotheosis.  I don't know if that is possible or not.

Additionally if you disable the enchant command fix the command becomes unavailable period.  Not even the vanilla one is available.  I did check and restarted the pack I'm using to the same effect.  I'll try to isolate to just the mod when I get a chance to verify what I see isn't something else but I don't have time right now.  Just wanted to note my observations for the new update.

**Comment by Fuzss** [comment]
Just pushed a fix for the command missing, had a boolean inverted.
For the proper Apotheosis caps to apply you'll have to disable both options and use the vanilla command. I'm replacing the whole command when any of my changes are applied, and that's when the Apotheosis changes stop working.
Thanks for testing!
