### ISSUE TITLE
[Bug]: Looting cannot be applied to swords with this mod

### ISSUE THREAD

**Issue by brisingraerowing** [Fuzss/universalenchants#35]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.9

### Notes (Required)

Current Behavior: Looting cannot be applied to swords
Expected Behavior: Looting can be applied to swords

1. Install mod
2. Try to apply looting to sword
3. Looting cannot be applied

**Comment by Fuzss** [comment]
Please be more clear for the steps you tried to apply looting: what sword, anvil/enchanting table/enchant command.
Also share your `.minecraft/config/universalenchants/looting.json` file if possible.

I just tried on a fresh install and looting can be applied as expected.

**Comment by brisingraerowing** [comment]
[looting.json](https://gist.github.com/brisingraerowing/636063845a53da83cfa6fc85b41c93c4)

It was a Diamond sword, though the file doesn't mention swords at all (that I saw)

**Comment by Fuzss** [comment]
Delete the file and let it regenerate. Send that new file again please. It must include $minecraft:weapon for swords to work. 

Also did you manually edit the file?

**Comment by brisingraerowing** [comment]
No manual editing. I'll regen the file in a bit. Currently trying to debug a lag issue.

**Comment by Fuzss** [comment]
Can you try this custom version please?
https://mega.nz/file/6ElRjRRY#-G2KiJsbzb4msyaeRAgrPk7wKPZHPfOFqZvBwJ65iaw

Ideally it should crash and be more clear about what is wrong, I need the crash report from that.

I looks like you have another mod that is trying to make tridents compatible with looting in an odd way. Do you have any idea what mod that might be?

**Comment by brisingraerowing** [comment]
I have Apotheosis, which does that. I was suspecting a compat issue with it.

**Comment by brisingraerowing** [comment]
The game did crash, but it was due to a different mod I updated earlier. Trying again with that reverted.

**Comment by brisingraerowing** [comment]
And the game loaded normally. The JSON config files weren't generated, though.

**Comment by Fuzss** [comment]
Can you just delete the whole universalenchants config folder? That will make it regenerate for sure. The send the new looting file.

**Comment by brisingraerowing** [comment]
That's what I did, and the custom file didn't recreate it at all.

**Comment by Fuzss** [comment]
Can you send the latest.log from that launch?

**Comment by Fuzss** [comment]
Oh an did you join a world? I think the files only generate when entering a world.

**Comment by brisingraerowing** [comment]
I figured that out a moment ago. I'll get the file in a moment. File Explorer is being stupid with locked folders / files again.

**Comment by brisingraerowing** [comment]
I just did a test with the KubeJS `list_tag` command, and the `#minecraft:weapon` tag doesn't even exist in the instance. Now to figure out why. I'm presuming that is the cause of the `$null` in the config.

**Comment by brisingraerowing** [comment]
[looting.json / latest.log](https://gist.github.com/brisingraerowing/f08b49794669362a80ff51197c3b7f300)

Here's the config / log files. I don't see anything of particular use.

**Comment by Fuzss** [comment]
$minecraft:weapon is not a tag. That link doesn’t seem to work.

**Comment by brisingraerowing** [comment]
There was an extra character at the end of the URL for some reason. Try it now.

**Comment by Fuzss** [comment]
This issue is becoming weirder and weirder, the last one should have really revealed something...

Here goes another one, both files again please and a crash report if one pops up:
https://mega.nz/file/PEtQzDyK#EbrPOoI1kdR1L0cNSgUB0BzPbHkTg1U4uPu3VXx5yAY

Also thanks a lot for helping with this!

**Comment by brisingraerowing** [comment]
The crash happened before the looting JSON file was generated.

[latest.log / Crash Report](https://gist.github.com/brisingraerowing/8d908557be131ebe8e1f383c265bb2b7)

**Comment by Fuzss** [comment]
Finally, that explains it. You have some mod that enables looting for axes, that is conflicting here. Do you have an idea what that might be?

I‘ll work on a fix tomorrow.

**Comment by brisingraerowing** [comment]
Ensorcellation does that.

**Comment by Fuzss** [comment]
Should be fixed in the latest v4.2.10. Can you confirm that?
