### ISSUE TITLE
[Crash]: Create New World button crashes after a few seconds after being clicked

### ISSUE THREAD

**Issue by vainlaind4in** [Fuzss/universalenchants#40]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.14

### Notes (Required)

1. Open game (with this mod alongside mods in modpack which is featured in report)
2. Click create new world
3. It crashes

This might have been discussed before in a different issue, but this has appeared on later versions of the mod. I assume it's a mod incompatibility.

### Crash Report (Required)

https://gist.github.com/vainlaind4in/ba54e1c7022f2ba57d05cef166169bec

### latest.log (Optional)

no

**Comment by Fuzss** [comment]
Thanks, fixed in v4.2.15.
