### ISSUE TITLE
[Suggestion]: Knockback on other Tools

### ISSUE THREAD

**Issue by K-Proj** [Fuzss/universalenchants#43]
Knockback is a universal bonus enchantment on any tool/weapon, and having the ability to knockback mobs/players without having to swap would be a nice QOL.

More interestingly though is how Knockback on Tools and Weapons interact with TNT Minecarts. Using knockback a player can launch TNT Minecarts without having to shove the cart (which could be quite dangerous) or use powered rails. But there's also a difference between how Tools and Weapons interact with the TNT Minecart though. With weapons such as Axes, Swords and even Tridents, hitting a TNT Minecart mid-air causes it to prime and explode quicker, and on the other hand, tools such as Hoes, Pickaxes and Shovels don't prime the cart and allow the player to knock the Cart farther.

In PVP or in specific misc. usage (such as terraforming), it would be nice being able to choose the type of knockback, whether weapon or tool, a small feature, and admittedly niche feature that's just not in Vanilla Minecraft as tools can't have knockback.

Here's a [Youtube Video](https://youtu.be/xa_UYPG-lsc) showcasing the differences between Tools and Weapon knockback interaction with a TNT Minecart.

**Comment by Fuzss** [comment]
Thanks for the suggestion! You can already enable knockback for more tools with the extensive configuration system this mod provides, look at the [README](https://github.com/Fuzss/universalenchants#configuring-the-mod) for that.

About TNT minecarts, this is interesting for sure, it's way too niche to dedicate time to.
