### ISSUE TITLE
[Bug]: Pickaxes can't be enchanted with Fire Aspect

### ISSUE THREAD

**Issue by yumm-dev** [Fuzss/universalenchants#45]
### Mod Loader

Fabric

### Minecraft Version

1.19.2

### Mod Version

v4.2.15

### Notes

I'm trying to enchant my pickaxe with Fire Aspect to take advantage of the `nerf_fire_aspect_on_tools = true` config option. However, trying to add it with an anvil results in the red 'X'.
Steps to reproduce:
1. Load up a world.
2. Place a pickaxe in the first slot and a Fire Aspect I enchantment book in the second slot.
Expected Results:
A pickaxe with Fire Aspect that will autosmelt blocks mined with it.

**Comment by Fuzss** [comment]
That feature was unfortunately removed since it felt out of scope and I forgot also remove the related config option. The option has properly been removed for the 1.19.3+ versions.

I might make a dedicated mod with new enchantments at some point and auto smelting will definitely be part of it.
