### ISSUE TITLE
[Suggestion]: Maybe a change or maybe an intentionally tweaked mechanic

### ISSUE THREAD

**Issue by esuqe** [Fuzss/universalenchants#48]
### Suggestion (Required)

On minecraft without mods if you have a sword with looting in primary hand and if you defeat a mob with a bow in the secondary hand, mob drops more items and xp but with this mod: fire aspect, looting, [freezing aspect and leeching aspect from other mods] does not apply those effects, still mobs defeated gives more experience.
If this was intentional, also make experience being affected by this mod.

**Comment by Fuzss** [comment]
This was an intentional change, since bows can be enchanted with looting now. But I understand that it can be confusing if you're used to the vanilla behavior. I've removed that part of the mod in one of the more recent ports (1.19.4 I think).
