### ISSUE TITLE
[Crash]: Universal Enchantments crashes games upon clicking on single player button on main menu

### ISSUE THREAD

**Issue by Nekkok** [Fuzss/universalenchants#53]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20

### Mod Version (Required)

UniversalEnchants-v7.0.0-1.20-Fabric

### Notes (Required)

1. Open game through Minecraft Official Launcher
2. Click single player
3. Let the game cook loading
4. Profit

Crash report and latest.log provides other mods installed

### Crash Report (Required)

https://gist.github.com/Nekkok/adbf013ce1169b3beb88ec067cc89e42

### latest.log (Optional)

https://gist.github.com/Nekkok/e7963150bbeb4f995515d68f744365c6

**Comment by Fuzss** [comment]
Thanks! This is a mod conflict. Can you please install this mod and let it crash again and send the new report?
https://modrinth.com/mod/mixintrace

**Comment by Fuzss** [comment]
Also separately from the mod above (I want that crash again to see what mod is interfering), you can try installing this one, which should fix the issue altogether.
https://mega.nz/file/Hd8A1ToB#cNgPvQwHxWzlYNZjrGCJmOG6qYFNyULThJnDtzInclY
Please let me know if it works.

**Comment by Fuzss** [comment]
This is publicly fixed in the 1.20.1 port. I've since dropped support for 1.20, but anyone with the same issue can just manually install the file I linked. Also is definitely just a conflict with another single mod, so the issue shouldn't be very widespread.
