### ISSUE TITLE
[Crash]: claims to be outdated

### ISSUE THREAD

**Issue by Flame39** [Fuzss/universalenchants#55]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

7.0.0

### Notes (Required)

Launcher functions perfectly fine, but when launching the game, it says this mod and Puzzles lib need 1.20 exactly, dispite this, other 1.20 programs seem to work just fine.

[crash-2023-06-16_20.57.38-fml.txt](https://github.com/Fuzss/universalenchants/files/11777786/crash-2023-06-16_20.57.38-fml.txt)

### Crash Report (Required)

idk

### latest.log (Optional)

uh... I put a file relating to the crash.

**Comment by Flame39** [comment]
(btw when do you plan to update straw and armor statues to 1.20.1)

**Comment by Fuzss** [comment]
Yes
