### ISSUE TITLE
[Bug]: Bow will not draw

### ISSUE THREAD

**Issue by IsriusQQ** [Fuzss/universalenchants#57]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

When using a bow, the bow draws to full immediately and no arrow is released when right click is released.
This happens even when the bow is not enchanted.
I've included a screenshot to show what I mean:
![2023-08-11_23 38 55](https://github.com/Fuzss/universalenchants/assets/122330988/687290bf-4512-4c07-9e9f-1f5bd0cfb9d9)
The bow is immediately drawn to full, but no arrow is fired after letting go of right click.

If the Quick Charge crossbow enchantment is applied to the bow, it will still draw to full immediately, an arrow is fired, but it doesn't shoot far, as if the bow wasn't charged at all.

I installed this mod in addition to a bunch of others, along with some that came as a part of the Fabulously Optimized modpack, but this bug seems to happen even when mods not necessary to run fabric are disabled.

Please let me know if there is any other information I can provide, and thank you for your time.

### latest.log (Optional)
https://gist.github.com/IsriusQQ/371461cbd2c8f79b852ab84c6b9e783f

**Comment by IsriusQQ** [comment]
Since my last post, I installed Universal Enchantments on a new instance of the Fabulously Optimized modpack, and the issue occurs there as well. I've attached the log from that launch as well, in case that helps.
[latest.log](https://github.com/Fuzss/universalenchants/files/12327454/latest.log)

The bug might be because of an incompatibility with one of the mods in that pack.

**Comment by Fuzss** [comment]
Thank you! The issue has just been fixed in the latest version of Puzzles Lib. Will take a few minutes to become available on CurseForge.
