### ISSUE TITLE
[Suggestion]: Delete Redundant Enchantments

### ISSUE THREAD

**Issue by Malachi-lewis** [Fuzss/universalenchants#60]
### Suggestion (Required)

Since this mod is making enchantments compatible with more items, I think it would also make sense to combine the ones that are literally the same except for the item they're applied to. These enchantments are:
Looting/Fortune/Luck of the Sea(I'd leave either looting or fortune)
Sharpness/Power(You'd have to keep Power)
Fire Aspect/Flame(Keep Fire Aspect)
Knockback/Punch(Knockback)
You could also merge Efficiency/Lure/Quick Charge, but that'd require messing with the levels.

**Comment by Fuzss** [comment]
Thanks for the suggestion, this is out of scope for this mod.
Here is another mod that works in a similar fashion to your suggestion: https://www.curseforge.com/minecraft/mc-mods/enchancement
