### ISSUE TITLE
[Bug]: modded enchants not taking effect

### ISSUE THREAD

**Issue by GreenForzeGaming** [Fuzss/universalenchants#64]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

latest for 1.20.1

### Notes (Required)

when i make enchantments from other mods available for new tools, in this case

endless quiver from apothioses: makes all arrows used infinite
this enchant when added too other tools in the config dosnt work in game even if they can get the enchant.
i put it on a cross bow. the crossbow still uses up arrows.
and if i put quick charge on a dart shooter from the aether mod its speed is not changed with reloading, same goes for the create potato cannon. idk why this is

**Comment by SiverDX** [comment]
Read the description:

> Please keep in mind that the internal implementation of individual enchantments is rather complex and relies on a bunch of hard-coded special cases. This means making enchantments compatible with new items has a good chance to not have any actual effect besides making the enchantment applicable to the item.

This is not solvable by this mod
