### ISSUE TITLE
[Suggestion]: Multishot on bows should spread arrows like on Crossbow

### ISSUE THREAD

**Issue by NeuTraLZero** [Fuzss/universalenchants#70]
### Suggestion (Required)

Right now it's just free damage since the arrows are shot really close together which allows for some insane damage with the Power enchantment especially on modded bows

**Comment by Fuzss** [comment]
I had this originally, but spreading the arrows horizontally doesn't make much sense with a bow. Maybe I'll change it to a vertical spread which would work from a logical point of view.

**Comment by Fuzss** [comment]
Added for 1.20.4.
