### ISSUE TITLE
[Crash]: trying to combine a crystal pickaxe with a fortune 3 book

### ISSUE THREAD

**Issue by MKALJANABY** [Fuzss/universalenchants#73]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.0.0

### Notes (Required)

open the anvil
shift click the crystal pickaxe from cyclic and then shift click the fortune 3 book

### Crash Report (Required)

https://gist.github.com/MKALJANABY/e3797e28702131d0815c621b92866bb7

### latest.log (Optional)

https://gist.github.com/MKALJANABY/1d062dc9dd1d40959be4be57853ed871

**Comment by Fuzss** [comment]
#74
