### ISSUE TITLE
Bug: Dedicated Server log spam when shutting down

### ISSUE THREAD

**Issue by Xaneas** [Fuzss/universalenchants#8]
I noticed that every time i shut down my Server PuzzlesLib in combination with Universal Enchants and Forge Config API Port spam the log with errors.
I don't know if the error is because of other mods, but the errors seem to only mention this 3 Mods.

Errors thrown in log when Server is shutting down:
```
[Thread-2/INFO]: Reloading server config for universalenchants
[Thread-2/ERROR]: Calling server config when it is not yet available! This is a bug! Current loading stage: MISSING_DATA
java.lang.Exception: Server config not yet available
```

### Info About the Server:
Minecraft Fabric 1.18.2
Fabric Loader Version 0.14.6
Mods loaded:60
PuzzlesLib: PuzzlesLib-v3.3.5-1.18.2-Fabric
Forge Config API: ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric
Universal Enchants: UniversalEnchants-v3.0.6-1.18.2-Fabric

Latest Log File: (Errors start at Line 270)
[latest.log](https://github.com/Fuzss/universalenchants-fabric/files/8827848/latest.log)

**Comment by Fuzss** [comment]
Resolved in v4.1.0 for 1.19 since the whole system has been overhauled.

Regarding 1.18, this is not a breaking bug, the spam essentially means nothing, it's just for me.
