### ISSUE TITLE
[Suggestion]:  Allow "god armor"

### ISSUE THREAD

**Issue by SebSemos** [Fuzss/universalenchants#80]
### Mod Loader (Optional)

Fabric

### Suggestion (Required)

Since with the mod we can already applied protection + another protection enchant to armors, why not going a step further and make it possible (again) to craft the so called god armor.
Could be disabled by default in config maybe.
But personnaly, I still got a fiew pieces from more than a week of 1.14 gring and I still disagree with mojang decision to remove this feature :p

**Comment by Fuzss** [comment]
The protection + specialized protection restriction is only the default configuration for the mod. You can easily edit the enchantment data files to allow all protection enchantments to coexist, see here: https://github.com/Fuzss/universalenchants/blob/main/README.md

**Comment by SebSemos** [comment]
Sick!!! Should have read the description more carefully 🤦‍♂️😁
