### ISSUE TITLE
Supplementary Static

### ISSUE THREAD

**Issue by GreenForzeGaming** [Fuzss/universalenchants#84]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

when 1.21.x

### Mod Version(s) (Optional)

when 1.21.x

### Suggestion (Required)

make the bow and crossbow shoot 0 gravity arrows and obviously make arrows despawn after a certen time if no blocks or entitys are hit

**Comment by winterveritas** [comment]
I don't think you understand what this mod is for.
Universal Enchants serves to expand upon the functionality and compatibility of pre-existing properties(enchantments, not as an augmentation outside the base game.
There is no enchantment that does what you are suggesting.
This mod does not, and nor is it intended to, add enchants to the game. Rendering your request outside the mod's scope.

**Comment by GreenForzeGaming** [comment]
whaa??? the mod supplementaries has a enchantment called static that lets its slingshot shots defy gravity. i thought it could be made so it works for bows and cross bows as its not right now. but maybe that has too be made on their side.

**Comment by Fuzss** [comment]
Yeah, the idea of Universal Enchants is to expand upon vanilla enchantments. Mods with their own enchantments can add additional features like that themselves. Thanks for the suggestion though!
